steps:
  - id: build-push
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=$_IMAGE_NAME
      - --cache=true
  - name: gcr.io/cloud-builders/gcloud
    waitFor:
      - build-push
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_IMAGE_NAME
      - --region=$_REGION
      - --platform=managed
      - --allow-unauthenticated
      - --service-account=$_SERVICE_ACCOUNT
      - --set-env-vars=IMAGE_BUCKET=$_IMAGE_BUCKET
timeout: 3600s
